name       : haskell-blaze-builder
version    : 0.4.0.2
release    : 1
source     :
    - http://hackage.haskell.org/package/blaze-builder-0.4.0.2/blaze-builder-0.4.0.2.tar.gz : 9ad3e4661bf5556d650fb9aa56a3ad6e6eec7575e87d472e8ab6d15eaef163d4
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides an implementation of the older blaze-builder interface in terms of the new builder that shipped with bytestring-0.10.4.0
description: |
    This library provides an implementation of the older blaze-builder interface in terms of the new builder that shipped with bytestring-0.10.4.0
builddeps  :
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
