name       : haskell-blaze-builder
version    : 0.4.1.0
release    : 3
source     :
    - https://hackage.haskell.org/package/blaze-builder-0.4.1.0/blaze-builder-0.4.1.0.tar.gz : 91fc8b966f3e9dc9461e1675c7566b881740f99abc906495491a3501630bc814
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides an implementation of the older blaze-builder interface in terms of the new builder that shipped with bytestring-0.10.4.0
description: |
    This library provides an implementation of the older blaze-builder interface in terms of the new builder that shipped with bytestring-0.10.4.0
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
